In [148]:
import numpy as np
from pandas import DataFrame
import pandas as pd
import scipy as sp
from sklearn.naive_bayes import GaussianNB

Reading files: 

In [149]:
train_data = sp.genfromtxt("data/train_data.txt", delimiter="\t")

test_data = sp.genfromtxt("data/test_data.txt", delimiter="\t")

val_data =  sp.genfromtxt("data/val_data.txt", delimiter="\t")

Dimensions:

In [150]:
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(858L, 25L)
(286L, 25L)
(286L, 25L)


In [151]:
train_data = train_data[~np.isnan(train_data).any(axis=1)]
test_data = test_data[~np.isnan(test_data).any(axis=1)]
val_data = val_data[~np.isnan(val_data).any(axis=1)]
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(857L, 25L)
(286L, 25L)
(286L, 25L)


Brisanje proba: 

In [152]:
train_data[:1]

array([[  4.79000000e+02,   8.10000000e+01,   2.29000000e+01,
          4.08000000e+00,   7.65000000e+00,   5.34000000e-01,
          1.00000000e-02,   4.00000000e-02,   1.76000000e-01,
          2.72000000e+00,   3.45000000e+00,   7.88000000e-01,
          1.98000000e+00,   3.03000000e+00,   5.01000000e+00,
          6.80000000e-01,   4.30000000e-01,   4.10000000e-01,
          2.39000000e+00,   1.22000000e+00,   1.08900000e+01,
          8.00000000e+00,   3.40000000e+01,   1.12000000e+02,
          2.06000000e+02]])

In [153]:
np.delete(train_data[:1], 1)

array([  4.79000000e+02,   2.29000000e+01,   4.08000000e+00,
         7.65000000e+00,   5.34000000e-01,   1.00000000e-02,
         4.00000000e-02,   1.76000000e-01,   2.72000000e+00,
         3.45000000e+00,   7.88000000e-01,   1.98000000e+00,
         3.03000000e+00,   5.01000000e+00,   6.80000000e-01,
         4.30000000e-01,   4.10000000e-01,   2.39000000e+00,
         1.22000000e+00,   1.08900000e+01,   8.00000000e+00,
         3.40000000e+01,   1.12000000e+02,   2.06000000e+02])

# Features

In [190]:
def np_featuriser(train, test, val,feature_lsit):
    
    train = np.delete(train,feature_list,1)
    test = np.delete(test,feature_list,1)
    val = np.delete(val,feature_list,1)
    
    return train, test, val


In [236]:
feature_list = [22]
train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

In [206]:
#train_features = np.delete(train_data, 22, 1)
#test_features = np.delete(test_data, 22, 1)
#val_features = np.delete(val_data,22,1)
                          
#train_features = np.delete(train_features, 21, 1)
#test_features = np.delete(test_features, 21, 1)
#val_features = np.delete(val_features,21,1)
                          
#print(train_features.shape)
#print(test_features.shape)
#print(val_features.shape)

columns = {"GP":0, "GS":1, "MIN":2, "FGM":3,"FGA":4,"FG%":5,"3PM":6,"3PA":7,"3P%":8,"FTM":9,"FTA":10,"FT%":11,"OFF":12,"DEF":13,
              "TRB":14,"AST":15,"STL":16,"BLK":17,"PF":18,"TOV":19,"PTS":20,"YR":21,"POS":22,"W":23,"H":24} 


# Univariate feature selection

In [216]:
from sklearn.feature_selection import SelectPercentile, f_classif
selector = SelectPercentile(f_classif, percentile=10)
X = train_features_nb
y = train_labels
#print X[:1]
selector.fit(X, y)
scores = -np.log10(selector.pvalues_)
print scores
scores /= scores.max()
print scores

#for i in scores:
#scores

print "Most valuable features: "
remove = []
for i in range(0,25):
    remove.append(i)
    
j = 0
for i in scores:
    
    if i>0.08:
        print j, i, columns.keys()[columns.values().index(j)]
        remove.remove(j)
    if j == 21:
        j = j+2
    else:
        j = j+1
#for i in range(0,25)
print remove

[  56.13927671   64.4679563    62.70453747   17.30301708   73.92406058
   27.41925933   42.04831989   75.91498997   28.98983588   59.2040295
  218.66202788  287.90107153]
[ 0.19499503  0.22392399  0.2177989   0.06010057  0.25676897  0.09523848
  0.14605128  0.26368429  0.10069374  0.20564018  0.75950404  1.        ]
Most valuable features: 
0 0.194995025223 GP
1 0.223923988737 GS
2 0.217798902703 MIN
4 0.256768966462 FGA
5 0.0952384761204 FG%
6 0.146051279598 3PM
7 0.263684291166 3PA
8 0.100693740809 3P%
9 0.205640184623 FTM
10 0.759504043217 FTA
11 1.0 FT%
[3, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [211]:
#feature_list = [0, 1, 2, 3, 4, 5, 9, 10, 18, 19, 20, 21, 22]
#train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

In [252]:
feature_list = [columns["GP"],columns["GS"],columns["MIN"],columns["FG%"],
      columns["3P%"],columns["FT%"],columns["PTS"],columns["YR"],columns["POS"],columns['3PM'],columns['FTM'],columns['FGM']]

train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

# Feature selection with VarianceThreshold 

In [253]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))


In [254]:
train_features_nb[:1]

array([[  7.65000000e+00,   4.00000000e-02,   3.45000000e+00,
          1.98000000e+00,   3.03000000e+00,   5.01000000e+00,
          6.80000000e-01,   4.30000000e-01,   4.10000000e-01,
          2.39000000e+00,   1.22000000e+00,   1.12000000e+02,
          2.06000000e+02]])

In [255]:
train_features_nb.shape

(857L, 13L)

In [256]:
sel.fit_transform(train_features_nb)[:1]
n = sel.fit_transform(train_features_nb)
m = sel.fit_transform(test_features_nb)

In [257]:
sel.fit_transform(train_features_nb)[:1].shape

(1L, 12L)

In [258]:
#train_features1 = sel.fit_transform(train_features)
#val_features1 = np.delete(val_features, 11, 1)
#train_features1.shape
#train_labels.shape

In [197]:
print "Training features dimensions: "  
print train_features_nb.shape
print "Test features dimensions: " 
print test_features_nb.shape
print "Validation features dimensions: "
print val_features_nb.shape

Training features dimensions: 
(857L, 11L)
Test features dimensions: 
(286L, 11L)
Validation features dimensions: 
(286L, 11L)


# Labels

In [198]:
train_labels = train_data[:,22]
test_labels = test_data[:,22]
val_labels = val_data[:,22]
print(train_labels.shape)
print(test_labels.shape)
print(val_labels.shape)

(857L,)
(286L,)
(286L,)


# Naive Bayes

In [259]:
clf = GaussianNB()

In [260]:
clf.fit(train_features_nb, train_labels)

GaussianNB()

In [261]:
pred = clf.predict(test_features_nb)

# Accuracy

In [263]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(pred, test_labels)
accuracy
#51% sa Variance Threshold
#53% with Univariate feature selection "SelectPercentile, f_classif"
#60% domensko znanjeI g

0.59790209790209792

# Custom Accuracy function

In [264]:
def custom_acc(pred_labels, test_labels):
    hit = 0
    num = 0
    j = 0
    for i in pred_labels:
        a = i
        a = str(int(a))
        b = test_labels[j]
        b = str(int(b))
        if a == b:
            hit = hit+1
        elif len(a) == 1 and len(b) == 2:
            if a == b[0] or a == b[1]:
                hit = hit+1
        elif len(a) == 2 and len(b) == 1:
            if a[0] == b or a[1] == b:
                hit = hit+1
        num = num+1
        j = j+1
    print num
    print hit
    return float(hit)/num


# Custom Accuracy NB

In [265]:
custom_acc(pred, test_labels)

286
241


0.8426573426573427

# Confusion matrix NB

In [266]:
from sklearn.metrics import confusion_matrix 

In [267]:
confm_nb = confusion_matrix(test_labels, pred)
confm_nb
#  labels 1 - 2 - 3- 4 - 5 - 12- 23- 34 - 45

array([[12,  0,  0,  0,  0,  2,  0,  0,  0],
       [ 2,  7,  3,  0,  0, 22,  2,  0,  0],
       [ 0,  0,  9,  0,  0,  1,  7,  3,  0],
       [ 0,  0,  0, 15, 13,  0,  0,  9,  2],
       [ 0,  0,  0,  1, 38,  0,  0,  0,  8],
       [ 2,  1,  0,  0,  0, 54,  2,  0,  0],
       [ 0,  0,  2,  0,  0,  1,  2,  0,  0],
       [ 0,  0,  1,  0,  8,  6,  7, 32,  0],
       [ 0,  0,  0,  1,  8,  0,  0,  1,  2]])

# SVM

In [273]:
from sklearn.svm import SVC

In [274]:
clfSVM= SVC()

In [275]:
clfSVM.set_params(kernel = 'linear')

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [276]:
clfSVM.fit(train_features_nb, train_labels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [277]:
predSVM = clfSVM.predict(test_features_nb)

# Accuracy SVM

In [280]:
accuracySVM = accuracy_score(predSVM, test_labels)
accuracySVM
# < 50% Variance threshold 
# 53% Univariate feature selection "SelectPercentile, f_classif"
# 57% Domain knowledge

0.57692307692307687

# Custom Accuracy SVM

In [281]:
custom_acc(predSVM, test_labels)

286
249


0.8706293706293706

# Confusion matrix SVM

In [282]:
confm_svm = confusion_matrix(test_labels, predSVM)
confm_svm
#  labels 1 - 2 - 3- 4 - 5 - 12- 23- 34 - 45

array([[ 8,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  8,  3,  0,  0, 25,  0,  0,  0],
       [ 0,  1, 11,  0,  0,  1,  2,  5,  0],
       [ 0,  0,  1, 13,  6,  0,  0, 15,  4],
       [ 0,  0,  0,  2, 42,  0,  0,  2,  1],
       [ 5,  3,  1,  0,  0, 47,  3,  0,  0],
       [ 0,  2,  1,  0,  0,  2,  0,  0,  0],
       [ 0,  1,  7,  1,  1,  1,  7, 34,  2],
       [ 0,  0,  0,  2,  5,  0,  0,  3,  2]])

# Logistic Regression

In [283]:
from sklearn import linear_model

In [284]:
logreg = linear_model.LogisticRegression(C=1e5)

In [285]:
logreg.fit(train_features_nb, train_labels)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0)

In [286]:
predLR = logreg.predict(test_features_nb)

# Logistic Regression Accuracy

In [288]:
accLR = accuracy_score(predLR, test_labels)
accLR
#50% Variance Threshold
#55% Univariate
#57% domain knowledge

0.56993006993006989

# Custom Accuracy SVM

In [289]:
custom_acc(predLR, test_labels)

286
240


0.8391608391608392

# Confusion matrix LR

In [290]:
confm_lr = confusion_matrix(test_labels, predLR)
confm_lr
#  labels 1 - 2 - 3- 4 - 5 - 12- 23- 34 - 45

array([[ 7,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  5,  1,  0,  0, 25,  1,  4,  0],
       [ 1,  3,  1,  0,  0,  3,  0, 12,  0],
       [ 0,  0,  0, 12,  9,  0,  0, 17,  1],
       [ 0,  0,  0,  1, 43,  0,  0,  2,  1],
       [ 2,  1,  0,  0,  0, 52,  0,  4,  0],
       [ 0,  1,  0,  0,  0,  2,  0,  2,  0],
       [ 0,  0,  0,  3,  2,  6,  1, 42,  0],
       [ 0,  0,  0,  1,  5,  0,  0,  5,  1]])