In [1]:
import numpy as np
from pandas import DataFrame
import pandas as pd
import scipy as sp
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn import linear_model
from sklearn.svm import SVC

Reading files: 

In [2]:
train_data = sp.genfromtxt("data/train_data.txt", delimiter="\t")

test_data = sp.genfromtxt("data/test_data.txt", delimiter="\t")

val_data =  sp.genfromtxt("data/val_data.txt", delimiter="\t")

Dimensions:

In [3]:
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(858L, 25L)
(286L, 25L)
(286L, 25L)


In [4]:
train_data = train_data[~np.isnan(train_data).any(axis=1)]
test_data = test_data[~np.isnan(test_data).any(axis=1)]
val_data = val_data[~np.isnan(val_data).any(axis=1)]
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(857L, 25L)
(286L, 25L)
(286L, 25L)


Brisanje proba: 

In [5]:
train_data[:1]

array([[  4.79000000e+02,   8.10000000e+01,   2.29000000e+01,
          4.08000000e+00,   7.65000000e+00,   5.34000000e-01,
          1.00000000e-02,   4.00000000e-02,   1.76000000e-01,
          2.72000000e+00,   3.45000000e+00,   7.88000000e-01,
          1.98000000e+00,   3.03000000e+00,   5.01000000e+00,
          6.80000000e-01,   4.30000000e-01,   4.10000000e-01,
          2.39000000e+00,   1.22000000e+00,   1.08900000e+01,
          8.00000000e+00,   3.40000000e+01,   1.12000000e+02,
          2.06000000e+02]])

In [6]:
np.delete(train_data[:1], 1)

array([  4.79000000e+02,   2.29000000e+01,   4.08000000e+00,
         7.65000000e+00,   5.34000000e-01,   1.00000000e-02,
         4.00000000e-02,   1.76000000e-01,   2.72000000e+00,
         3.45000000e+00,   7.88000000e-01,   1.98000000e+00,
         3.03000000e+00,   5.01000000e+00,   6.80000000e-01,
         4.30000000e-01,   4.10000000e-01,   2.39000000e+00,
         1.22000000e+00,   1.08900000e+01,   8.00000000e+00,
         3.40000000e+01,   1.12000000e+02,   2.06000000e+02])

# Features

In [7]:
def np_featuriser(train, test, val,feature_list):
    
    train = np.delete(train,feature_list,1)
    test = np.delete(test,feature_list,1)
    val = np.delete(val,feature_list,1)
    
    return train, test, val


In [8]:
train_all, test_all, val_all = np_featuriser(train_data, test_data, val_data,22)

# Labels

In [9]:
train_labels = train_data[:,22]
test_labels = test_data[:,22]
val_labels = val_data[:,22]
print(train_labels.shape)
print(test_labels.shape)
print(val_labels.shape)

(857L,)
(286L,)
(286L,)


In [10]:
feature_list = [22]
train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

In [11]:
#train_features = np.delete(train_data, 22, 1)
#test_features = np.delete(test_data, 22, 1)
#val_features = np.delete(val_data,22,1)
                          
#train_features = np.delete(train_features, 21, 1)
#test_features = np.delete(test_features, 21, 1)
#val_features = np.delete(val_features,21,1)
                          
#print(train_features.shape)
#print(test_features.shape)
#print(val_features.shape)

columns = {"GP":0, "GS":1, "MIN":2, "FGM":3,"FGA":4,"FG%":5,"3PM":6,"3PA":7,"3P%":8,"FTM":9,"FTA":10,"FT%":11,"OFF":12,"DEF":13,
              "TRB":14,"AST":15,"STL":16,"BLK":17,"PF":18,"TOV":19,"PTS":20,"YR":21,"POS":22,"W":23,"H":24} 


# Univariate feature selection

In [12]:
from sklearn.feature_selection import SelectPercentile, f_classif
selector = SelectPercentile(f_classif, percentile=10)
X = train_features_nb
y = train_labels
#print X[:1]
selector.fit(X, y)
scores = -np.log10(selector.pvalues_)
print scores
scores /= scores.max()
print scores

#for i in scores:
#scores

print "Most valuable features: "
remove = []
for i in range(0,25):
    remove.append(i)
    
j = 0
for i in scores:
    
    if i>0.19:
        print j, i, columns.keys()[columns.values().index(j)]
        remove.remove(j)
    if j == 21:
        j = j+2
    else:
        j = j+1
#for i in range(0,25)
print remove

[  3.94708354e+00   3.31676009e+00   6.03282416e+00   6.24335941e+00
   1.11107171e+01   1.36120482e+01   5.61392767e+01   6.44679563e+01
   6.27045375e+01   3.40120889e+00   1.82896326e+00   1.73030171e+01
   7.39240606e+01   2.74192593e+01   4.20483199e+01   7.59149900e+01
   2.89898359e+01   5.92040295e+01   1.25166265e+01   1.07926258e+01
   7.75632294e+00   1.39091934e-01   2.18662028e+02   2.87901072e+02]
[  1.37098606e-02   1.15204854e-02   2.09545040e-02   2.16857804e-02
   3.85921353e-02   4.72802970e-02   1.94995025e-01   2.23923989e-01
   2.17798903e-01   1.18138112e-02   6.35274904e-03   6.01005651e-02
   2.56768966e-01   9.52384761e-02   1.46051280e-01   2.63684291e-01
   1.00693741e-01   2.05640185e-01   4.34754427e-02   3.74872721e-02
   2.69409311e-02   4.83124057e-04   7.59504043e-01   1.00000000e+00]
Most valuable features: 
6 0.194995025223 3PM
7 0.223923988737 3PA
8 0.217798902703 3P%
12 0.256768966462 OFF
15 0.263684291166 AST
17 0.205640184623 BLK
23 0.75950404321

In [13]:
#feature_list = [0, 1, 2, 3, 4, 5, 9, 10, 18, 19, 20, 21, 22]
#train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

In [14]:
feature_list = [columns["GP"],columns["GS"],columns["MIN"],columns["FG%"],
      columns["3P%"],columns["FT%"],columns["PTS"],columns["YR"],columns["POS"],columns['3PM'],columns['FTM'],columns['FGM']]

train_features_nb, test_features_nb, val_features_nb = np_featuriser(train_data, test_data, val_data, feature_list )

# Feature selection with VarianceThreshold 

In [15]:
from sklearn.feature_selection import VarianceThreshold



In [16]:
def vt_fsel(train):
    sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
    sel.fit_transform(train)
    vt_list = sel.get_support()
    l_vt = []
    j = 0
    for i in vt_list:
        if i == False:
            l_vt.append(j)
            print "%s. featue name: %s" %(j, columns.keys()[columns.values().index(j)])
        j = j+1
    return l_vt    

In [17]:
list_vt = vt_fsel(train_data)

5. featue name: FG%
8. featue name: 3P%
11. featue name: FT%
16. featue name: STL


In [18]:
#train_features1 = sel.fit_transform(train_features)
#val_features1 = np.delete(val_features, 11, 1)
#train_features1.shape
#train_labels.shape

In [19]:
print "Training features dimensions: "  
print train_features_nb.shape
print "Test features dimensions: " 
print test_features_nb.shape
print "Validation features dimensions: "
print val_features_nb.shape

Training features dimensions: 
(857L, 13L)
Test features dimensions: 
(286L, 13L)
Validation features dimensions: 
(286L, 13L)


# Custom Accuracy function

In [20]:
def custom_acc(pred_labels, test_labels):
    hit = 0
    num = 0
    j = 0
    for i in pred_labels:
        a = i
        a = str(int(a))
        b = test_labels[j]
        b = str(int(b))
        if a == b:
            hit = hit+1
        elif len(a) == 1 and len(b) == 2:
            if a == b[0] or a == b[1]:
                hit = hit+1
        elif len(a) == 2 and len(b) == 1:
            if a[0] == b or a[1] == b:
                hit = hit+1
        num = num+1
        j = j+1
    #print num
    #print hit
    return float(hit)/num


# All Results

In [21]:
list_none = [22]
list_domain = [columns["GP"],columns["GS"],columns["MIN"],columns["FG%"],
      columns["3P%"],columns["FT%"],columns["PTS"],columns["YR"],columns["POS"],columns['3PM'],columns['FTM'],columns['FGM']]
list_uni = [0, 2, 4, 5, 7, 9, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [22]:
def print_metrics(name, accuracy, c_acc, conf_matrix):
    print "Feature selection: %s\n" %name
    print "Accuracy score: %s\n" %accuracy
    print "Custom Accuracy score: %s\n" %c_acc
    print "Confusion matrix:"
    print "\n%s" %conf_matrix
    print"\n"
    
def clf(clf, tr, tr_labels, val, val_labels):
        clf.fit(tr, tr_labels)
        
        pred = clf.predict(val)
        
        acc = metrics.accuracy_score(val_labels,pred)
        c_acc = custom_acc(pred, val_labels)
        conf = metrics.confusion_matrix(val_labels, pred)
        
        return acc, c_acc, conf

In [23]:
def clf_all(CLF, l_none, l_domain, l_uni, l_vt, train_all, test_all, val_all):
    tr_none, ts_none, val_none = np_featuriser(train_all, test_all, val_all, l_none)
    #print tr_none.shape
    tr_domain, ts_domain, val_domain = np_featuriser(train_all, test_all, val_all, l_domain)
    
    tr_uni, ts_uni, val_uni = np_featuriser(train_all, test_all, val_all, l_uni)
    
    tr_vt, ts_vt, val_vt = np_featuriser(train_all, test_all, val_all, l_vt)
    
    #clfnb = GaussianNB()
    #print "Naive Bayes\n"
    
    acc_none, c_acc, conf_none = clf(CLF, tr_none, train_labels, val_none, val_labels)
    print_metrics("None", acc_none, c_acc, conf_none)
    
    acc_domain, c_acc, conf_domain = clf(CLF, tr_domain, train_labels, val_domain, val_labels)
    print_metrics("Domain knowledge", acc_domain, c_acc, conf_domain)

    acc_uni,c_acc, conf_uni = clf(CLF, tr_uni, train_labels, val_uni, val_labels)
    print_metrics("Univariate", acc_uni, c_acc, conf_uni)
    
    acc_vt, c_acc, conf_vt = clf(CLF, tr_vt, train_labels, val_vt, val_labels)
    print_metrics("Variance Threshold", acc_vt, c_acc, conf_vt)

In [24]:
clfnb = GaussianNB()
clf_all(clfnb, list_none, list_domain, list_uni, list_vt, train_all, test_all, val_all)

Feature selection: None

Accuracy score: 0.527972027972

Custom Accuracy score: 0.741258741259

Confusion matrix:

[[10  0  0  0  0  4  0  0  0]
 [ 2 11  3  0  2 15  3  0  0]
 [ 0  1 10  0  0  1  4  4  0]
 [ 0  0  0 13 18  0  0  4  4]
 [ 0  0  0  3 36  0  0  0  8]
 [ 2  0  0  0  1 53  3  0  0]
 [ 0  1  2  0  0  1  1  0  0]
 [ 0  0  1  1 27  3  7 15  0]
 [ 0  0  0  0  8  0  0  2  2]]


Feature selection: Domain knowledge

Accuracy score: 0.583916083916

Custom Accuracy score: 0.832167832168

Confusion matrix:

[[10  0  0  0  0  4  0  0  0]
 [ 1  8  3  0  0 23  1  0  0]
 [ 0  0 10  0  0  2  5  3  0]
 [ 0  0  0 14 11  0  0 11  3]
 [ 0  0  0  1 38  0  0  0  8]
 [ 2  1  0  0  0 55  1  0  0]
 [ 0  0  2  0  0  2  1  0  0]
 [ 0  0  1  1 12  5  6 29  0]
 [ 0  0  0  0  6  0  0  4  2]]


Feature selection: Univariate

Accuracy score: 0.381118881119

Custom Accuracy score: 0.524475524476

Confusion matrix:

[[ 0  7  0  0  2  5  0  0  0]
 [ 0 10  4  0  2 19  0  1  0]
 [ 0  4  5  2  3  6  0  0  0]
 

In [25]:
svm = SVC()
svm.set_params(kernel='linear')
clf_all(svm, list_none, list_domain, list_uni, list_vt, train_all, test_all, val_all)

Feature selection: None

Accuracy score: 0.618881118881

Custom Accuracy score: 0.902097902098

Confusion matrix:

[[ 7  0  0  0  0  7  0  0  0]
 [ 0 14  0  0  0 21  1  0  0]
 [ 0  2  9  0  0  1  3  5  0]
 [ 0  0  0 17  5  0  0 14  3]
 [ 0  0  0  1 42  0  0  3  1]
 [ 3  3  2  0  0 51  0  0  0]
 [ 0  2  1  0  0  2  0  0  0]
 [ 0  0  6  4  3  2  2 37  0]
 [ 0  0  0  2  5  0  0  5  0]]


Feature selection: Domain knowledge

Accuracy score: 0.583916083916

Custom Accuracy score: 0.877622377622

Confusion matrix:

[[ 8  0  0  0  0  6  0  0  0]
 [ 0  8  1  0  0 26  1  0  0]
 [ 0  1  9  0  0  2  4  4  0]
 [ 0  0  1 11  7  0  0 16  4]
 [ 0  0  0  3 42  0  0  1  1]
 [ 2  2  0  0  0 53  1  1  0]
 [ 0  2  1  0  0  2  0  0  0]
 [ 0  0  3  4  2  2  6 35  2]
 [ 0  0  0  3  5  0  0  3  1]]


Feature selection: Univariate

Accuracy score: 0.405594405594

Custom Accuracy score: 0.629370629371

Confusion matrix:

[[ 0  0  1  0  0 13  0  0  0]
 [ 0  1  2  0  0 28  0  5  0]
 [ 0  0  2  1  2 10  0  5  0]
 

In [26]:
logreg = linear_model.LogisticRegression(C=1e5)
clf_all(logreg, list_none, list_domain, list_uni, list_vt, train_all, test_all, val_all)

Feature selection: None

Accuracy score: 0.548951048951

Custom Accuracy score: 0.79020979021

Confusion matrix:

[[ 6  0  0  0  0  8  0  0  0]
 [ 1  8  3  0  0 20  0  4  0]
 [ 0  2  4  4  0  2  0  8  0]
 [ 0  0  0 14 12  0  0 12  1]
 [ 0  0  0  1 44  0  0  1  1]
 [ 8  0  0  0  0 43  1  7  0]
 [ 0  1  0  0  0  2  0  2  0]
 [ 0  0  0  4  5  6  1 38  0]
 [ 0  0  0  1  5  0  0  6  0]]


Feature selection: Domain knowledge

Accuracy score: 0.555944055944

Custom Accuracy score: 0.818181818182

Confusion matrix:

[[ 5  0  0  0  0  9  0  0  0]
 [ 0  5  1  0  0 25  1  4  0]
 [ 0  2  1  2  0  3  0 12  0]
 [ 0  0  0 15 12  0  0 12  0]
 [ 0  0  0  0 43  0  0  3  1]
 [ 3  1  0  0  0 51  0  4  0]
 [ 0  0  0  0  0  2  0  3  0]
 [ 0  0  0  3  5  6  1 39  0]
 [ 0  0  0  2  6  0  0  4  0]]


Feature selection: Univariate

Accuracy score: 0.409090909091

Custom Accuracy score: 0.622377622378

Confusion matrix:

[[ 1  0  1  0  0 12  0  0  0]
 [ 1  1  1  0  0 25  0  8  0]
 [ 0  0  3  1  2 10  0  4  0]
 [