In [53]:
import numpy as np
from pandas import DataFrame
import pandas as pd
import scipy as sp
from sklearn.naive_bayes import GaussianNB

Učitavanje fajlova: 

In [54]:
train_data = sp.genfromtxt("train_data.txt", delimiter="\t")

test_data = sp.genfromtxt("test_data.txt", delimiter="\t")

val_data =  sp.genfromtxt("val_data.txt", delimiter="\t")

Dimenzije:

In [55]:
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(858L, 25L)
(286L, 25L)
(286L, 25L)


In [56]:
train_data = train_data[~np.isnan(train_data).any(axis=1)]
test_data = test_data[~np.isnan(test_data).any(axis=1)]
val_data = val_data[~np.isnan(val_data).any(axis=1)]
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(857L, 25L)
(286L, 25L)
(286L, 25L)


Brisanje proba: 

In [57]:
train_data[:1]

array([[  4.79000000e+02,   8.10000000e+01,   2.29000000e+01,
          4.08000000e+00,   7.65000000e+00,   5.34000000e-01,
          1.00000000e-02,   4.00000000e-02,   1.76000000e-01,
          2.72000000e+00,   3.45000000e+00,   7.88000000e-01,
          1.98000000e+00,   3.03000000e+00,   5.01000000e+00,
          6.80000000e-01,   4.30000000e-01,   4.10000000e-01,
          2.39000000e+00,   1.22000000e+00,   1.08900000e+01,
          8.00000000e+00,   3.40000000e+01,   1.12000000e+02,
          2.06000000e+02]])

In [58]:
np.delete(train_data[:1], 1)

array([  4.79000000e+02,   2.29000000e+01,   4.08000000e+00,
         7.65000000e+00,   5.34000000e-01,   1.00000000e-02,
         4.00000000e-02,   1.76000000e-01,   2.72000000e+00,
         3.45000000e+00,   7.88000000e-01,   1.98000000e+00,
         3.03000000e+00,   5.01000000e+00,   6.80000000e-01,
         4.30000000e-01,   4.10000000e-01,   2.39000000e+00,
         1.22000000e+00,   1.08900000e+01,   8.00000000e+00,
         3.40000000e+01,   1.12000000e+02,   2.06000000e+02])

# Features

In [59]:
#train_features = np.delete(train_data, 22, 1)
#test_features = np.delete(test_data, 22, 1)
#val_features = np.delete(val_data,22,1)
                          
#train_features = np.delete(train_features, 21, 1)
#test_features = np.delete(test_features, 21, 1)
#val_features = np.delete(val_features,21,1)
                          
#print(train_features.shape)
#print(test_features.shape)
#print(val_features.shape)

columns = {"GP":0, "GS":1, "MIN":2, "FGM":3,"FGA":4,"FG%":5,"3PM":6,"3PA":7,"3P%":8,"FTM":9,"FTA":10,"FT%":11,"OFF":12,"DEF":13,
              "TRB":14,"AST":15,"STL":16,"BLK":17,"PF":18,"TOV":19,"PTS":20,"YR":21,"POS":22,"W":23,"H":24} 


In [60]:
def remove_multiple_features(feature_list):
    
    fl = sorted(feature_list,reverse=True)
    #print fl
    train_features = train_data
    test_features = test_data
    val_features = val_data
    
    for i in fl:
        #print i
        train_features = np.delete(train_features, i, 1)
        #print i
        test_features = np.delete(test_features, i, 1)
        #print i
        val_features = np.delete(val_features,i,1)
        
    print(train_features.shape)
    print(test_features.shape)
    print(val_features.shape)
    return [train_features, test_features, val_features]

In [61]:
print(train_data.shape)
print(test_data.shape)
print(val_data.shape)

(857L, 25L)
(286L, 25L)
(286L, 25L)


In [62]:
fl = [columns["GP"],columns["GS"],columns["MIN"],columns["FG%"],
      columns["3P%"],columns["FT%"],columns["PTS"],columns["YR"],columns["POS"]]

In [63]:
features = remove_multiple_features(fl)
train_features = features[0]
test_features = features[1]
val_features = features[2]

(857L, 16L)
(286L, 16L)
(286L, 16L)


# Labels

In [65]:
train_labels = train_data[:,22]
test_labels = test_data[:,22]
val_labels = val_data[:,22]
print(train_labels.shape)
print(test_labels.shape)
print(val_labels.shape)

(857L,)
(286L,)
(286L,)


# Naive Bayes

In [66]:
clf = GaussianNB()

In [67]:
clf.fit(train_features, train_labels)

GaussianNB()

In [68]:
pred = clf.predict(test_features)
pred

array([ 12.,   1.,   5.,  45.,   3.,   3.,   4.,   5.,  12.,  34.,  12.,
         5.,   4.,  45.,  12.,  12.,  12.,   5.,  12.,   5.,   5.,   3.,
         5.,  34.,  12.,  12.,  34.,   1.,  12.,   1.,   4.,  34.,  12.,
         5.,  12.,  12.,   5.,  34.,  12.,  12.,   5.,   5.,  34.,  23.,
         3.,   5.,  12.,  12.,   5.,  12.,   5.,  45.,  34.,  12.,   5.,
         5.,  34.,  12.,   5.,  12.,   5.,   5.,   5.,  12.,   5.,  34.,
        34.,  12.,  12.,   5.,  12.,   4.,   2.,   5.,  12.,  12.,  12.,
         5.,  45.,   5.,  12.,  23.,  12.,  23.,   1.,   3.,  34.,  23.,
         5.,   5.,  12.,   1.,  12.,   3.,   5.,  12.,  23.,  23.,   5.,
         5.,  23.,  23.,  45.,   2.,   3.,   5.,   5.,   5.,   5.,  34.,
         5.,   5.,  12.,  23.,   1.,  12.,   5.,   5.,   3.,   5.,  34.,
         5.,  34.,   3.,   2.,   4.,   4.,  34.,   1.,   5.,  34.,   5.,
         5.,   1.,  45.,   5.,   1.,   4.,  12.,  45.,   4.,   1.,   5.,
        34.,   4.,   1.,  12.,   2.,  23.,   5.,   

In [69]:
test_labels

array([  2.,   1.,   5.,   5.,   2.,   3.,   4.,  45.,  12.,   4.,  12.,
        34.,   4.,  45.,  12.,   2.,  12.,  45.,   2.,  45.,  34.,   3.,
         5.,  34.,   3.,   2.,  34.,   1.,  12.,   1.,   5.,  34.,  12.,
         4.,  12.,   2.,   4.,  34.,   2.,  12.,   4.,  34.,  34.,   3.,
         3.,   4.,  12.,  12.,   4.,   2.,   5.,  45.,  34.,  12.,   4.,
         5.,  34.,  12.,  45.,  12.,   5.,   5.,   5.,  12.,  34.,  34.,
        34.,  12.,  12.,   4.,   2.,   4.,   2.,   5.,  12.,   2.,   2.,
        45.,   5.,   5.,  12.,   2.,   1.,   2.,   1.,   2.,  34.,  34.,
         5.,  34.,  12.,   2.,   2.,   2.,  34.,  34.,   3.,  34.,   4.,
         4.,  12.,  34.,  45.,   2.,  23.,   4.,  34.,   4.,  34.,  34.,
        34.,   4.,  12.,  12.,   1.,  12.,   5.,  34.,   3.,   5.,   3.,
        45.,  34.,   3.,   2.,   4.,   4.,  34.,   1.,   5.,   4.,   5.,
         4.,   1.,   5.,   5.,   1.,   4.,   2.,   4.,   4.,   2.,  34.,
         3.,   4.,  12.,  12.,   2.,   3.,   5.,  3

# Preciznost

In [70]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(pred, test_labels)
accuracy

0.56993006993006989

# Custom preciznost

In [71]:
def custom_acc(pred_labels, test_labels):
    hit = 0
    num = 0
    j = 0
    for i in pred_labels:
        a = i
        a = str(int(a))
        b = test_labels[j]
        b = str(int(b))
        if a == b:
            hit = hit+1
        elif len(a) == 1 and len(b) == 2:
            if a == b[0] or a == b[1]:
                hit = hit+1
        elif len(a) == 2 and len(b) == 1:
            if a[0] == b or a[1] == b:
                hit = hit+1
        num = num+1
        j = j+1
    print num
    print hit
    return float(hit)/num


In [72]:
custom_acc(pred, test_labels)

286
226


0.7902097902097902

# Validation     

In [73]:
pred2 = clf.predict(val_features)
pred2

array([ 12.,   1.,   5.,  45.,   3.,   3.,   4.,   5.,  12.,  34.,  12.,
         5.,   4.,  45.,  12.,  12.,  12.,   5.,  12.,   5.,   5.,   3.,
         5.,  34.,  12.,  12.,  34.,   1.,  12.,   1.,   4.,  34.,  12.,
         5.,  12.,  12.,   5.,  34.,  12.,  12.,   5.,   5.,  34.,  23.,
         3.,   5.,  12.,  12.,   5.,  12.,   5.,  45.,  34.,  12.,   5.,
         5.,  34.,  12.,   5.,  12.,   5.,   5.,   5.,  12.,   5.,  34.,
        34.,  12.,  12.,   5.,  12.,   4.,   2.,   5.,  12.,  12.,  12.,
         5.,  45.,   5.,  12.,  23.,  12.,  23.,   1.,   3.,  34.,  23.,
         5.,   5.,  12.,   1.,  12.,   3.,   5.,  12.,  23.,  23.,   5.,
         5.,  23.,  23.,  45.,   2.,   3.,   5.,   5.,   5.,   5.,  34.,
         5.,   5.,  12.,  23.,   1.,  12.,   5.,   5.,   3.,   5.,  34.,
         5.,  34.,   3.,   2.,   4.,   4.,  34.,   1.,   5.,  34.,   5.,
         5.,   1.,  45.,   5.,   1.,   4.,  12.,  45.,   4.,   1.,   5.,
        34.,   4.,   1.,  12.,   2.,  23.,   5.,   

In [74]:
accuracy2 = accuracy_score(pred2, val_labels)
accuracy2

0.56993006993006989

In [75]:
custom_acc(pred2, val_labels)

286
226


0.7902097902097902

# SVM

In [71]:
from sklearn.svm import SVC

In [73]:
clf2 = SVC()

In [75]:
clf2.fit(train_features, train_labels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [79]:
pred2 = clf2.predict(test_features)

In [80]:
accuracy2 = accuracy_score(pred2, test_labels)
accuracy2

0.20820189274447951